#!/usr/bin/env node
/* Append new idioms to src/data/idioms.json. Skips duplicates by
   both id AND case-insensitive text. Re-runnable. */

import fs from "node:fs";
const FILE = "src/data/idioms.json";

const NEW_IDIOMS = [
  // ── Animals ─────────────────────────────────────────────────
  { id: "id-cat-among-pigeons", text: "put the cat among the pigeons", meaning: "to do or say something that causes trouble and makes people angry", tags: ["mischief","animals"] },
  { id: "id-cats-pajamas", text: "the cat's pajamas", meaning: "an excellent person or thing", tags: ["praise","animals"] },
  { id: "id-pig-poke", text: "a pig in a poke", meaning: "something bought or accepted without first being inspected", tags: ["caution","commerce"] },
  { id: "id-hog-heaven", text: "in hog heaven", meaning: "extremely happy or contented", tags: ["happiness","animals"] },
  { id: "id-eat-crow", text: "eat crow", meaning: "to admit one was wrong, often humiliatingly", tags: ["regret","truth"] },
  { id: "id-elephant-room", text: "the elephant in the room", meaning: "an obvious problem nobody wants to discuss", tags: ["awkward","truth"] },
  { id: "id-monkey-back", text: "get the monkey off one's back", meaning: "to free oneself of a long-standing problem or burden", tags: ["relief","struggle"] },
  { id: "id-monkey-business", text: "monkey business", meaning: "silly, dishonest, or mischievous activity", tags: ["mischief","work"] },
  { id: "id-monkeys-uncle", text: "well, I'll be a monkey's uncle", meaning: "an expression of complete surprise", tags: ["surprise","exclamation"] },
  { id: "id-cat-got-tongue", text: "has the cat got your tongue", meaning: "asked of someone who is unexpectedly silent", tags: ["silence","speaking"] },
  { id: "id-curiosity-killed-cat", text: "curiosity killed the cat", meaning: "being too inquisitive can lead to trouble", tags: ["caution","warning"] },
  { id: "id-fish-other-fry", text: "have other fish to fry", meaning: "to have more important things to do", tags: ["priority","work"] },
  { id: "id-fish-water", text: "a fish out of water", meaning: "someone in an uncomfortable or unfamiliar situation", tags: ["discomfort","misfit"] },
  { id: "id-bull-china-shop", text: "a bull in a china shop", meaning: "a person who is clumsy in a delicate situation", tags: ["clumsy","damage"] },
  { id: "id-take-bull-horns", text: "take the bull by the horns", meaning: "to confront a problem head-on with courage", tags: ["courage","action"] },
  { id: "id-cock-bull", text: "a cock and bull story", meaning: "a far-fetched, untrue tale", tags: ["lies","stories"] },
  { id: "id-snake-grass", text: "a snake in the grass", meaning: "a treacherous or deceitful person", tags: ["betrayal","warning"] },
  { id: "id-wolf-sheep-clothing", text: "a wolf in sheep's clothing", meaning: "someone hiding malice behind a kind appearance", tags: ["deception","warning"] },
  { id: "id-cry-wolf", text: "to cry wolf", meaning: "to raise a false alarm so often that real ones are ignored", tags: ["warning","trust"] },
  { id: "id-lion-share", text: "the lion's share", meaning: "the largest part of something", tags: ["portion","power"] },
  { id: "id-paper-tiger", text: "a paper tiger", meaning: "someone or something that seems threatening but is actually weak", tags: ["appearance","weakness"] },
  { id: "id-rabbit-hat", text: "pull a rabbit out of a hat", meaning: "to produce an unexpected solution at the last moment", tags: ["surprise","problem-solving"] },
  { id: "id-rabbit-hole", text: "go down the rabbit hole", meaning: "to enter into a complex, bewildering, or absorbing situation", tags: ["complexity","exploration"] },
  { id: "id-frog-throat", text: "a frog in one's throat", meaning: "hoarseness or difficulty speaking due to phlegm", tags: ["body","speaking"] },
  { id: "id-goose-chase", text: "a wild goose chase", meaning: "a hopeless, fruitless quest", tags: ["futility","waste"] },
  { id: "id-cooking-goose", text: "your goose is cooked", meaning: "you are in serious trouble with no way out", tags: ["trouble","ruin"] },
  { id: "id-sitting-duck", text: "a sitting duck", meaning: "someone or something easy to attack or deceive", tags: ["vulnerable","easy"] },
  { id: "id-duck-water", text: "like a duck to water", meaning: "naturally suited to or comfortable with a new activity", tags: ["ability","natural"] },
  { id: "id-ugly-duckling", text: "an ugly duckling", meaning: "someone who develops from an unpromising start into something admirable", tags: ["growth","change"] },
  { id: "id-busy-as-bee", text: "as busy as a bee", meaning: "very hard at work", tags: ["work","industrious"] },
  { id: "id-bee-bonnet", text: "a bee in one's bonnet", meaning: "an obsession or persistent worry about something", tags: ["obsession","worry"] },
  { id: "id-birds-feather", text: "birds of a feather flock together", meaning: "similar people tend to associate with each other", tags: ["friendship","sociology"] },
  { id: "id-early-bird", text: "the early bird catches the worm", meaning: "those who act promptly succeed", tags: ["promptness","success"] },
  { id: "id-night-owl", text: "a night owl", meaning: "a person who stays up and is most active late at night", tags: ["habits","time"] },
  { id: "id-dog-fight", text: "fight like cats and dogs", meaning: "to argue or quarrel constantly", tags: ["conflict","argument"] },
  { id: "id-let-sleeping-dogs", text: "let sleeping dogs lie", meaning: "to leave a situation alone to avoid causing new trouble", tags: ["caution","peace"] },
  { id: "id-dog-bark-wrong", text: "barking up the wrong tree", meaning: "to make a mistake about where to look for something", tags: ["mistake","misdirection"] },
  { id: "id-dog-house", text: "in the doghouse", meaning: "in trouble with someone, especially a partner", tags: ["trouble","relationships"] },
  { id: "id-tail-wagging-dog", text: "the tail wagging the dog", meaning: "a small or unimportant part controlling the whole", tags: ["power","priority"] },
  { id: "id-bark-worse-bite", text: "his bark is worse than his bite", meaning: "someone seems harsher than they really are", tags: ["appearance","character"] },

  // ── Body & physical ─────────────────────────────────────────
  { id: "id-cold-shoulder", text: "give someone the cold shoulder", meaning: "to deliberately ignore someone", tags: ["rejection","social"] },
  { id: "id-shoulder-cry", text: "a shoulder to cry on", meaning: "a sympathetic listener in times of distress", tags: ["comfort","support"] },
  { id: "id-elbow-grease", text: "elbow grease", meaning: "hard physical effort", tags: ["work","effort"] },
  { id: "id-elbow-room", text: "elbow room", meaning: "space to move or work freely", tags: ["space","freedom"] },
  { id: "id-knee-jerk", text: "a knee-jerk reaction", meaning: "an automatic, unthinking response", tags: ["reaction","impulsive"] },
  { id: "id-foot-mouth", text: "put your foot in your mouth", meaning: "to say something tactless or embarrassing", tags: ["mistake","speaking"] },
  { id: "id-foot-door", text: "get a foot in the door", meaning: "to gain an initial entry to an organization or industry", tags: ["opportunity","start"] },
  { id: "id-feet-ground", text: "keep your feet on the ground", meaning: "stay practical and realistic", tags: ["sensible","practical"] },
  { id: "id-bite-tongue", text: "bite your tongue", meaning: "to stop yourself from saying something", tags: ["restraint","silence"] },
  { id: "id-hold-tongue", text: "hold your tongue", meaning: "stay silent, especially to avoid trouble", tags: ["silence","restraint"] },
  { id: "id-tip-tongue", text: "on the tip of my tongue", meaning: "almost remembered but not quite recalled", tags: ["memory","speaking"] },
  { id: "id-slip-tongue", text: "a slip of the tongue", meaning: "a minor unintended verbal mistake", tags: ["mistake","speaking"] },
  { id: "id-ears-burning", text: "my ears are burning", meaning: "I feel that someone is talking about me", tags: ["gossip","superstition"] },
  { id: "id-all-ears", text: "I'm all ears", meaning: "I'm listening with full attention", tags: ["listening","attention"] },
  { id: "id-deaf-ears", text: "fall on deaf ears", meaning: "to be ignored despite being heard", tags: ["ignored","listening"] },
  { id: "id-eye-eye", text: "see eye to eye", meaning: "to agree completely", tags: ["agreement","relationships"] },
  { id: "id-eye-needle", text: "the eye of the needle", meaning: "a very narrow opening, literal or figurative", tags: ["difficulty","passage"] },
  { id: "id-keep-eye", text: "keep an eye on", meaning: "to watch carefully", tags: ["attention","watching"] },
  { id: "id-eye-storm", text: "the eye of the storm", meaning: "the calm at the center of a difficult situation", tags: ["calm","crisis"] },
  { id: "id-eyes-back-head", text: "have eyes in the back of your head", meaning: "to be very observant of everything around you", tags: ["observation","awareness"] },
  { id: "id-nose-grindstone", text: "keep your nose to the grindstone", meaning: "to work hard and steadily", tags: ["work","diligence"] },
  { id: "id-nose-out-joint", text: "put one's nose out of joint", meaning: "to offend or annoy", tags: ["offense","social"] },
  { id: "id-pay-nose", text: "pay through the nose", meaning: "to pay an exorbitant amount", tags: ["money","cost"] },
  { id: "id-under-nose", text: "right under your nose", meaning: "very close by, but unnoticed", tags: ["obvious","hidden"] },
  { id: "id-stick-neck-out", text: "stick your neck out", meaning: "to take a risk to help someone", tags: ["risk","courage"] },
  { id: "id-pain-neck", text: "a pain in the neck", meaning: "an annoying person or thing", tags: ["annoyance","complaint"] },
  { id: "id-breathe-down-neck", text: "breathe down someone's neck", meaning: "to monitor or pressure someone closely", tags: ["pressure","oversight"] },
  { id: "id-head-clouds", text: "have your head in the clouds", meaning: "to be lost in daydreams or unrealistic thinking", tags: ["dreaming","unrealistic"] },
  { id: "id-head-water", text: "keep your head above water", meaning: "to manage to survive a difficult situation", tags: ["survival","struggle"] },
  { id: "id-lose-head", text: "lose your head", meaning: "to panic or become uncontrollably emotional", tags: ["panic","emotion"] },
  { id: "id-bite-head-off", text: "bite someone's head off", meaning: "to respond to someone harshly and angrily", tags: ["anger","harshness"] },
  { id: "id-hands-tied", text: "my hands are tied", meaning: "I am unable to act because of rules or constraints", tags: ["helpless","restriction"] },
  { id: "id-hand-mouth", text: "live from hand to mouth", meaning: "to have just enough money to survive day to day", tags: ["poverty","survival"] },
  { id: "id-hand-on-heart", text: "with my hand on my heart", meaning: "speaking with complete sincerity", tags: ["honesty","sincerity"] },
  { id: "id-give-hand", text: "give someone a hand", meaning: "to help, or to applaud", tags: ["help","support"] },
  { id: "id-hand-glove", text: "hand in glove", meaning: "in close cooperation, often for dubious ends", tags: ["cooperation","conspiracy"] },
  { id: "id-arm-leg", text: "cost an arm and a leg", meaning: "to be extremely expensive", tags: ["money","cost"] },
  { id: "id-leg-up", text: "give someone a leg up", meaning: "to help someone succeed or get started", tags: ["help","support"] },
  { id: "id-pull-leg", text: "pull someone's leg", meaning: "to tease or joke playfully", tags: ["humor","teasing"] },
  { id: "id-not-leg-stand", text: "not have a leg to stand on", meaning: "to have no support for one's position", tags: ["weakness","argument"] },
  { id: "id-tongue-cheek", text: "tongue in cheek", meaning: "spoken ironically or as a joke", tags: ["humor","irony"] },
  { id: "id-thumbs-up", text: "give the thumbs up", meaning: "to indicate approval", tags: ["approval","communication"] },
  { id: "id-thumb-rule", text: "a rule of thumb", meaning: "a broadly accurate guide based on experience", tags: ["guideline","practical"] },
  { id: "id-finger-pulse", text: "have your finger on the pulse", meaning: "to be fully aware of current developments", tags: ["awareness","trends"] },
  { id: "id-finger-pies", text: "have a finger in every pie", meaning: "to be involved in many different activities", tags: ["involvement","busy"] },
  { id: "id-pointing-finger", text: "point the finger", meaning: "to accuse or blame someone", tags: ["blame","accusation"] },

  // ── Money & commerce ────────────────────────────────────────
  { id: "id-bring-home-bacon", text: "bring home the bacon", meaning: "to earn money for the family", tags: ["money","work"] },
  { id: "id-tighten-belt", text: "tighten your belt", meaning: "to economize or live more frugally", tags: ["frugality","money"] },
  { id: "id-burn-bridges", text: "burn your bridges", meaning: "to permanently damage a relationship or option", tags: ["regret","relationships"] },
  { id: "id-burn-candle", text: "burn the candle at both ends", meaning: "to exhaust yourself by overworking", tags: ["exhaustion","overwork"] },
  { id: "id-cash-cow", text: "a cash cow", meaning: "a business or product that reliably generates profit", tags: ["money","business"] },
  { id: "id-money-talks", text: "money talks", meaning: "wealth gives people influence", tags: ["money","power"] },
  { id: "id-not-penny-rub", text: "not have two pennies to rub together", meaning: "to be very poor", tags: ["poverty","money"] },
  { id: "id-penny-pincher", text: "a penny pincher", meaning: "someone unwilling to spend money", tags: ["frugality","character"] },
  { id: "id-rolling-dough", text: "rolling in dough", meaning: "to be very wealthy", tags: ["wealth","money"] },
  { id: "id-foot-bill", text: "foot the bill", meaning: "to pay for something, especially for a group", tags: ["money","payment"] },
  { id: "id-pay-piper", text: "pay the piper", meaning: "to face the consequences of past actions", tags: ["consequence","payment"] },
  { id: "id-pretty-penny", text: "a pretty penny", meaning: "a large sum of money", tags: ["money","cost"] },
  { id: "id-strike-gold", text: "strike gold", meaning: "to find or achieve something very valuable", tags: ["success","discovery"] },
  { id: "id-cut-mustard", text: "cut the mustard", meaning: "to meet expected standards", tags: ["competence","ability"] },
  { id: "id-bring-table", text: "bring something to the table", meaning: "to contribute something valuable in a discussion or partnership", tags: ["contribution","value"] },
  { id: "id-back-burner", text: "put on the back burner", meaning: "to delay action on something less important", tags: ["delay","priority"] },
  { id: "id-tighten-screws", text: "tighten the screws on", meaning: "to apply pressure to force action", tags: ["pressure","force"] },
  { id: "id-pulling-strings", text: "pull some strings", meaning: "to use personal influence to obtain a favor", tags: ["influence","favor"] },
  { id: "id-call-shots", text: "call the shots", meaning: "to be in charge and make decisions", tags: ["control","authority"] },
  { id: "id-rule-roost", text: "rule the roost", meaning: "to be the dominant person in a group", tags: ["control","leadership"] },

  // ── Time & timing ───────────────────────────────────────────
  { id: "id-time-flies", text: "time flies", meaning: "time passes quickly, especially when you're enjoying it", tags: ["time","perception"] },
  { id: "id-time-is-money", text: "time is money", meaning: "wasted time is wasted earning potential", tags: ["time","money"] },
  { id: "id-twelfth-hour", text: "at the eleventh hour", meaning: "at the very last possible moment", tags: ["time","urgency"] },
  { id: "id-time-essence", text: "time is of the essence", meaning: "speed is critically important", tags: ["time","urgency"] },
  { id: "id-clock-watch", text: "watch the clock", meaning: "to count the minutes until something ends", tags: ["impatience","boredom"] },
  { id: "id-against-clock", text: "race against the clock", meaning: "to hurry to finish before a deadline", tags: ["urgency","deadline"] },
  { id: "id-cross-bridge", text: "cross that bridge when we come to it", meaning: "to deal with a problem only when it actually arises", tags: ["postponement","practical"] },
  { id: "id-out-frying-pan", text: "out of the frying pan and into the fire", meaning: "to escape one bad situation only to enter a worse one", tags: ["trouble","escape"] },
  { id: "id-irons-fire", text: "have too many irons in the fire", meaning: "to be involved in too many activities at once", tags: ["overcommit","busy"] },
  { id: "id-not-rocket-science", text: "it's not rocket science", meaning: "it's not difficult to understand", tags: ["simple","clarity"] },
  { id: "id-back-square-one", text: "back to square one", meaning: "having to start over after a failed attempt", tags: ["restart","failure"] },
  { id: "id-back-drawing-board", text: "back to the drawing board", meaning: "needing to start planning again from the beginning", tags: ["restart","planning"] },
  { id: "id-better-late-never", text: "better late than never", meaning: "doing something eventually is better than not at all", tags: ["timing","action"] },
  { id: "id-haste-makes-waste", text: "haste makes waste", meaning: "rushing leads to mistakes", tags: ["caution","speed"] },
  { id: "id-look-before-leap", text: "look before you leap", meaning: "consider risks before acting", tags: ["caution","planning"] },
  { id: "id-leap-of-faith", text: "take a leap of faith", meaning: "to believe in or attempt something despite uncertainty", tags: ["risk","trust"] },
  { id: "id-going-grain", text: "go against the grain", meaning: "to do something opposite to the usual way", tags: ["nonconformity","difference"] },
  { id: "id-blow-fuse", text: "blow a fuse", meaning: "to lose one's temper suddenly", tags: ["anger","outburst"] },
  { id: "id-blow-top", text: "blow your top", meaning: "to become extremely angry", tags: ["anger","outburst"] },
  { id: "id-hit-roof", text: "hit the roof", meaning: "to react with intense anger", tags: ["anger","reaction"] },
  { id: "id-fly-handle", text: "fly off the handle", meaning: "to lose one's temper abruptly", tags: ["anger","temper"] },
  { id: "id-keep-cool", text: "keep your cool", meaning: "to remain calm under stress", tags: ["calm","composure"] },
  { id: "id-cool-cucumber", text: "cool as a cucumber", meaning: "very calm and composed", tags: ["calm","composure"] },
  { id: "id-keep-shirt-on", text: "keep your shirt on", meaning: "calm down; don't lose patience", tags: ["calm","patience"] },

  // ── Knowledge, communication ─────────────────────────────────
  { id: "id-read-lines", text: "read between the lines", meaning: "to infer meaning beyond what's directly stated", tags: ["understanding","perception"] },
  { id: "id-cards-table", text: "lay your cards on the table", meaning: "to be open about one's intentions or plans", tags: ["honesty","openness"] },
  { id: "id-cards-vest", text: "play your cards close to the vest", meaning: "to keep your plans secret", tags: ["secrecy","caution"] },
  { id: "id-go-board", text: "across the board", meaning: "affecting everyone or everything", tags: ["universal","scope"] },
  { id: "id-on-board", text: "on board with something", meaning: "in agreement with a plan or idea", tags: ["agreement","support"] },
  { id: "id-rock-boat", text: "rock the boat", meaning: "to disturb a stable situation", tags: ["disruption","change"] },
  { id: "id-miss-boat", text: "miss the boat", meaning: "to miss an opportunity", tags: ["missed","opportunity"] },
  { id: "id-same-boat", text: "in the same boat", meaning: "facing the same difficult situation as another", tags: ["solidarity","shared"] },
  { id: "id-ship-sailed", text: "that ship has sailed", meaning: "the opportunity has already passed", tags: ["missed","finality"] },
  { id: "id-running-tight", text: "run a tight ship", meaning: "to manage strictly and efficiently", tags: ["discipline","management"] },
  { id: "id-jump-ship", text: "jump ship", meaning: "to abandon a project or organization in trouble", tags: ["abandonment","crisis"] },
  { id: "id-pulled-rug", text: "pull the rug out from under", meaning: "to withdraw support suddenly", tags: ["betrayal","abandonment"] },
  { id: "id-bend-over-backwards", text: "bend over backwards", meaning: "to make extraordinary efforts to help", tags: ["effort","helpful"] },
  { id: "id-go-extra-mile", text: "go the extra mile", meaning: "to do more than what is expected", tags: ["effort","dedication"] },
  { id: "id-go-with-flow", text: "go with the flow", meaning: "to accept the natural progression of events", tags: ["acceptance","ease"] },
  { id: "id-swim-against-current", text: "swim against the current", meaning: "to act against prevailing opinion", tags: ["nonconformity","resistance"] },
  { id: "id-rise-occasion", text: "rise to the occasion", meaning: "to perform well in a challenging situation", tags: ["excellence","challenge"] },
  { id: "id-bite-off-chew", text: "bite off more than you can chew", meaning: "to take on more than you can manage", tags: ["overcommit","overreach"] },
  { id: "id-on-cloud-nine", text: "on cloud nine", meaning: "extremely happy or joyful", tags: ["happiness","emotion"] },
  { id: "id-over-moon", text: "over the moon", meaning: "extremely delighted", tags: ["happiness","emotion"] },
  { id: "id-walking-air", text: "walking on air", meaning: "feeling elated and happy", tags: ["happiness","joy"] },
  { id: "id-down-dumps", text: "down in the dumps", meaning: "feeling sad and dejected", tags: ["sadness","mood"] },
  { id: "id-feel-blue", text: "feeling blue", meaning: "feeling sad or melancholy", tags: ["sadness","mood"] },
  { id: "id-out-blue", text: "out of the blue", meaning: "unexpectedly, without warning", tags: ["surprise","sudden"] },
  { id: "id-once-lifetime", text: "a once-in-a-lifetime opportunity", meaning: "a chance that may never come again", tags: ["opportunity","rare"] },
  { id: "id-needle-haystack", text: "a needle in a haystack", meaning: "something very difficult to find", tags: ["difficulty","searching"] },
  { id: "id-burst-bubble", text: "burst someone's bubble", meaning: "to deliver disappointing news that ends a happy mood", tags: ["disappointment","reality"] },
  { id: "id-rain-parade", text: "rain on someone's parade", meaning: "to spoil someone's enjoyment", tags: ["disappointment","spoiling"] },
  { id: "id-silver-platter", text: "on a silver platter", meaning: "given easily, without having to work for it", tags: ["easy","reward"] },
  { id: "id-grain-salt", text: "take it with a grain of salt", meaning: "to view a claim with skepticism", tags: ["skepticism","caution"] },
  { id: "id-piece-mind", text: "give someone a piece of your mind", meaning: "to express anger frankly", tags: ["confrontation","anger"] },
  { id: "id-clear-air", text: "clear the air", meaning: "to resolve misunderstandings through honest discussion", tags: ["resolution","communication"] },
  { id: "id-hit-nail-head", text: "hit the nail on the head", meaning: "to describe something exactly right", tags: ["accuracy","truth"] },
  { id: "id-call-spade", text: "call a spade a spade", meaning: "to speak plainly without euphemism", tags: ["honesty","plainness"] },
  { id: "id-mountain-molehill", text: "make a mountain out of a molehill", meaning: "to exaggerate the importance of a small problem", tags: ["exaggeration","drama"] },
  { id: "id-cross-fingers", text: "keep your fingers crossed", meaning: "to hope for a good outcome", tags: ["hope","luck"] },
  { id: "id-knock-wood", text: "knock on wood", meaning: "said to ward off bad luck after a positive statement", tags: ["luck","superstition"] },
  { id: "id-fingers-burnt", text: "get your fingers burnt", meaning: "to suffer because of an unwise involvement", tags: ["regret","consequence"] },
  { id: "id-blessing-disguise", text: "a blessing in disguise", meaning: "something unfortunate that turns out to be good", tags: ["luck","perspective"] },
  { id: "id-silver-lining", text: "every cloud has a silver lining", meaning: "every difficult situation has something positive in it", tags: ["optimism","hope"] },
  { id: "id-light-tunnel", text: "light at the end of the tunnel", meaning: "hope that a difficult period will end soon", tags: ["hope","relief"] },
  { id: "id-icing-cake", text: "the icing on the cake", meaning: "an extra good thing on top of an already good one", tags: ["bonus","extra"] },
  { id: "id-cherry-top", text: "the cherry on top", meaning: "a final perfect touch", tags: ["bonus","extra"] },
  { id: "id-best-both", text: "the best of both worlds", meaning: "the advantages of two contrasting situations together", tags: ["balance","advantage"] },
  { id: "id-cut-from-cloth", text: "cut from the same cloth", meaning: "very similar in character or temperament", tags: ["similarity","kinship"] },
  { id: "id-chip-off-block", text: "a chip off the old block", meaning: "someone who closely resembles a parent in character", tags: ["heredity","similarity"] },
  { id: "id-apple-eye", text: "the apple of one's eye", meaning: "a deeply cherished person", tags: ["love","affection"] },
  { id: "id-rotten-apple", text: "one rotten apple spoils the barrel", meaning: "one bad person can corrupt a whole group", tags: ["corruption","influence"] },
  { id: "id-apple-tree", text: "the apple doesn't fall far from the tree", meaning: "children resemble their parents", tags: ["heredity","family"] },
  { id: "id-comparing-apples-oranges", text: "comparing apples and oranges", meaning: "comparing two unlike things", tags: ["comparison","logic"] },
  { id: "id-sour-grapes", text: "sour grapes", meaning: "pretending to dislike what one cannot have", tags: ["envy","denial"] },
  { id: "id-grapevine", text: "I heard it through the grapevine", meaning: "I learned it through unofficial channels or gossip", tags: ["gossip","rumor"] },
  { id: "id-spilling-tea", text: "spill the tea", meaning: "to share gossip or revealing information", tags: ["gossip","sharing"] },
  { id: "id-from-scratch", text: "from scratch", meaning: "from the very beginning, with no prior preparation", tags: ["beginning","origin"] },
  { id: "id-square-one", text: "back at square one", meaning: "right back where one started", tags: ["restart","start"] },
  { id: "id-cut-to-chase", text: "cut to the chase", meaning: "to skip the preliminaries and get to the point", tags: ["directness","speed"] },
  { id: "id-bottom-line", text: "the bottom line", meaning: "the most important final point", tags: ["conclusion","important"] },
  { id: "id-long-short", text: "to make a long story short", meaning: "to give a brief summary", tags: ["brevity","summary"] },
  { id: "id-cut-long", text: "to cut a long story short", meaning: "to summarize the key point of a longer tale", tags: ["brevity","summary"] },
  { id: "id-talk-walk", text: "walk the talk", meaning: "to act in accordance with what one says", tags: ["integrity","action"] },
  { id: "id-walk-mile", text: "walk a mile in someone's shoes", meaning: "to try to see things from another's perspective", tags: ["empathy","perspective"] },
  { id: "id-cross-line", text: "cross the line", meaning: "to behave unacceptably", tags: ["offense","boundary"] },
  { id: "id-draw-line", text: "draw the line", meaning: "to set a limit on what is acceptable", tags: ["limit","boundary"] },
  { id: "id-fine-line", text: "a fine line between", meaning: "a small but important distinction", tags: ["distinction","subtlety"] },
  { id: "id-rough-around", text: "rough around the edges", meaning: "lacking polish but good underneath", tags: ["unrefined","character"] },
  { id: "id-cream-crop", text: "the cream of the crop", meaning: "the very best of a group", tags: ["best","quality"] },
  { id: "id-creme-creme", text: "the crème de la crème", meaning: "the finest of all", tags: ["best","excellence"] },
  { id: "id-top-line", text: "top of the line", meaning: "the highest quality of its kind", tags: ["best","quality"] },
  { id: "id-bottom-barrel", text: "scrape the bottom of the barrel", meaning: "to use the least desirable option because nothing else is left", tags: ["last-resort","poor"] },
  { id: "id-tough-cookie", text: "a tough cookie", meaning: "a strong-willed or resilient person", tags: ["strength","character"] },
  { id: "id-piece-pie", text: "a piece of the pie", meaning: "a share of something valuable", tags: ["share","reward"] },
  { id: "id-easy-pie", text: "easy as pie", meaning: "very easy to do", tags: ["easy","simple"] },
  { id: "id-no-piece-cake", text: "no piece of cake", meaning: "not easy at all", tags: ["difficulty","challenge"] },
  { id: "id-bread-butter", text: "bread and butter", meaning: "one's main source of income", tags: ["money","work"] },
  { id: "id-best-bread", text: "the best thing since sliced bread", meaning: "an exceptionally good innovation", tags: ["praise","innovation"] },
  { id: "id-bread-winner", text: "the breadwinner", meaning: "the person whose income supports the family", tags: ["money","family"] },
  { id: "id-bring-bacon", text: "save someone's bacon", meaning: "to rescue someone from trouble", tags: ["rescue","help"] },
  { id: "id-cold-turkey", text: "go cold turkey", meaning: "to quit something addictive abruptly", tags: ["quitting","health"] },
  { id: "id-talk-turkey", text: "talk turkey", meaning: "to discuss something seriously and frankly", tags: ["honesty","business"] },
  { id: "id-walking-eggshells", text: "walking on eggshells", meaning: "being very careful not to upset someone", tags: ["caution","tact"] },
  { id: "id-egg-face", text: "egg on your face", meaning: "embarrassed by an obvious mistake", tags: ["embarrassment","mistake"] },
  { id: "id-egg-someone-on", text: "egg someone on", meaning: "to encourage someone to do something foolish", tags: ["encouragement","mischief"] },
  { id: "id-piping-hot", text: "piping hot", meaning: "extremely hot, freshly cooked", tags: ["food","hot"] },
  { id: "id-flash-pan", text: "a flash in the pan", meaning: "a brief success unlikely to be repeated", tags: ["temporary","success"] },
  { id: "id-out-pocket", text: "out of pocket", meaning: "having to pay from one's own funds", tags: ["money","payment"] },
  { id: "id-deep-pockets", text: "deep pockets", meaning: "having plenty of money", tags: ["wealth","money"] },
  { id: "id-shoot-breeze", text: "shoot the breeze", meaning: "to chat casually", tags: ["conversation","relaxed"] },
  { id: "id-chew-fat", text: "chew the fat", meaning: "to talk informally about random topics", tags: ["conversation","relaxed"] },
  { id: "id-side-tracked", text: "get sidetracked", meaning: "to be distracted from the main task", tags: ["distraction","focus"] },
  { id: "id-end-rope", text: "at the end of my rope", meaning: "having no more patience or resources", tags: ["exhaustion","frustration"] },
  { id: "id-end-tether", text: "at the end of my tether", meaning: "no longer able to cope", tags: ["exhaustion","frustration"] },
  { id: "id-living-edge", text: "living on the edge", meaning: "taking many risks in life", tags: ["risk","adventure"] },
  { id: "id-pin-down", text: "pin someone down", meaning: "to get someone to commit definitely", tags: ["commitment","specifics"] },
  { id: "id-toe-line", text: "toe the line", meaning: "to follow rules and meet expectations", tags: ["obedience","conformity"] },
  { id: "id-by-book", text: "by the book", meaning: "exactly according to the rules", tags: ["rules","strict"] },
  { id: "id-throw-towel", text: "throw in the towel", meaning: "to give up after struggling", tags: ["surrender","quitting"] },
  { id: "id-pull-plug", text: "pull the plug", meaning: "to terminate or end something", tags: ["ending","cancel"] },
  { id: "id-give-up-ghost", text: "give up the ghost", meaning: "to stop functioning, or to die", tags: ["death","failure"] },
  { id: "id-down-count", text: "down for the count", meaning: "defeated or out of action", tags: ["defeat","failure"] },
  { id: "id-skin-teeth", text: "by the skin of one's teeth", meaning: "just barely; by a narrow margin", tags: ["narrow","escape"] },
  { id: "id-hair-trigger", text: "on a hair trigger", meaning: "ready to react explosively at the slightest provocation", tags: ["sensitive","reaction"] },
  { id: "id-toothpaste-tube", text: "you can't put toothpaste back in the tube", meaning: "some things, once done or said, cannot be undone", tags: ["finality","regret"] },
];

const data = JSON.parse(fs.readFileSync(FILE, "utf8"));
const existingIds = new Set(data.map((x) => x.id));
const existingTexts = new Set(data.map((x) => x.text.toLowerCase().trim()));
let added = 0, skipped = 0;
for (const i of NEW_IDIOMS) {
  if (existingIds.has(i.id) || existingTexts.has(i.text.toLowerCase().trim())) { skipped++; continue; }
  data.push(i);
  existingIds.add(i.id);
  existingTexts.add(i.text.toLowerCase().trim());
  added++;
}
fs.writeFileSync(FILE, JSON.stringify(data, null, 2));
console.log("idioms: added " + added + ", skipped (duplicates) " + skipped + ", total now " + data.length);
