export default [
  {
    date: "2026-05-08",
    title: "Contribute system, blog, completion tracking, fullscreen, modal swap",
    tag: "v0.4",
    notes: [
      "/contribute/ hub with eight Web3Forms-backed forms: quote, book, parable, idiom, poem, drill, testimonial, thanks-note",
      "Smart /thank-you/ confirmation page tailors its message based on ?for=<kind>",
      "/reviews/ and /thanks-wall/ public pages -- approval-required curation via _data/reviews.js and _data/thanks_notes.js",
      "Per-corpus 'Suggest a...' CTAs at the bottom of /quotes/, /idioms/, /parables/, /poetry/, /library/, /drills/",
      "Megamenu and footer gained a Contribute column",
      "Post-session inline 'Leave a testimonial' prompt after 10+ lifetime sessions, dismissable",
      "/blog/ launched with Atom RSS at /feed.xml, tag pages, sticky TOC, reading-progress bar, social share, drop cap, prev/next nav",
      "Three starter posts: contribute system, completion tracking, why no em-dash",
      "Completion tracking rewritten -- only items typed all-the-way-through (endCursor >= targetLen) at >=80% accuracy mark complete",
      "Per-item and bulk reset on every corpus page (quotes, idioms, parables, poetry) and book detail page",
      "corpusProgress slice on every profile mirrors bookProgress: { quote, idiom, parable, poem }",
      "Native confirm() and prompt() replaced site-wide with styled <dialog> modals -- focus-trapped, theme-aware, cancel auto-focused on destructive actions",
      "Em-dashes (--) replaced with ASCII double-hyphen across UI, content, lessons, drills, megamenu, and book ingest pipeline",
      "Paragraph breaks now visible during book typing -- engine renders each paragraph as a block element with one space char joining them",
      "Engine now exposes endCursor + targetLen + book mode in finish triggers",
      "Contextual back link above the typing surface -- 'Back to quotes / idioms / parables / poetry / book / lessons / custom'",
      "Attribution header above quote/parable/poem/idiom typing -- title, author, year, source, meaning",
      "Tab+Enter restart replaces Alt+R -- two-key combo prevents accidental restart and avoids NVIDIA overlay collision",
      "Header gained a Fullscreen button (Lucide maximize-2 icon) right of Settings, toggles native Fullscreen API",
      "Streak chip simplified -- 'X day' instead of 'X day streak'",
      "Footer fits all 7 columns on one row at >=1180px (container widens to 96vw, max 1480px)",
      "Home page typing surface restored -- daily quote is now typeable inline, finish jumps to /practice/ for full results",
      "Weak-keys widget on the results card now session-scoped (filters out chars not in the just-typed target)",
      "Fixed mode-best card overflow at narrow viewports (220px min, flex-wrap on values, ellipsis on long labels)",
      "Default preferences flipped -- virtual keyboard ON, finger colors ON (v3 -> v4 migration)",
      "Quotes page is full-width with 'Type this' + 'Save to collection' actions, Random quote button, no pangrams in quote data",
    ],
  },
  {
    date: "2026-05-07",
    title: "Site named: Guerilla Type",
    tag: "v0.3",
    notes: [
      "New name: Guerilla Type at guerillatype.com",
      "New brand mark, favicon set, and OG card",
      "Toolbar groups now have visible legends — Mode, Duration, Word count, Quote length",
      "Live stats: third metric label changes per mode (seconds left / words typed / complete %)",
      "Keyboard shortcuts overlay (press ? or Ctrl+/) with g-prefix navigation",
      "Daily streak chip in the header (when ≥ 1 day)",
      "Session WPM-over-time mini chart in the results card",
      "Sticky-TOC click now scrolls to the precise section (header offset accounted for)",
      "Lesson, drill, and adaptive sessions now save properly (auto-finish at end)",
      "Heatmap visualizes keys with ≥ 2 samples (was ≥ 5) so first sessions show data",
    ],
  },
  {
    date: "2026-05-07",
    title: "Editorial pivot, megamenus, and informative pages",
    tag: "v0.2",
    notes: [
      "New visual identity: warm-paper editorial palette, persimmon accent, Lora serif display",
      "Megamenu nav with categorized sub-links (Practice, Learn, Compete, Insights)",
      "Daily quote on the home page — one curated quote per visitor per day",
      "Lessons now genuinely restrict the typing surface to their declared key set",
      "Backspace in the engine no longer freezes the keystroke pipeline",
      "New informative pages: Features, Tech stack, Analytics, Cost — all with sticky TOCs",
      "About, FAQ, Privacy, Terms rewritten and migrated to article layout",
    ],
  },
  {
    date: "2026-05-07",
    title: "Initial release",
    tag: "v0.1",
    notes: [
      "Practice modes: time, words, quote, zen, custom, adaptive",
      "Adaptive engine with weak-key + bigram targeting",
      "Custom text upload and saved-text manager",
      "Stats dashboard: lifetime totals, trend chart, contribution grid, keyboard heatmap, per-key bars",
      "Eleven challenges shipped, including code mode and mountain climb",
      "Four keyboard layouts (QWERTY/Dvorak/Colemak/Workman) for heatmap rendering",
      "Profiles with JSON export/import. localStorage only, no accounts.",
    ],
  },
];
