export default [
  {
    date: "2026-09-02",
    title: "Scanned books come out clean: OCR noise, running heads, and a typeable corpus",
    tag: "v0.7",
    notes: [
      "Scanner-noise cleanup for imported text. Guillemets and other quote look-alikes become straight quotes (with the French inner space removed along with the guillemet), clipped ellipses are repaired ('?..' becomes '?...'), and stray scanner glyphs (* ^ | \\ ~ \u2022 \u00b0 < > \u2122) are dropped -- but only when three guards say it is safe. A glyph in a run survives (**bold**, scene breaks), a glyph next to a digit survives (x^2, 5*3, 20\u00b0C), and a glyph standing alone between spaces survives (a < b). A caret welded inside a word (all^r) is debris and goes; measured on a real 530-page scan, 110 of 131 welded glyphs were junk and none were legitimate.",
      "Cleanup runs on import AND on display, so books imported before this existed are repaired the next time you open them -- no re-import needed. The cleaner is idempotent: re-cleaning cleaned text changes nothing, which matters because the practice page re-cleans on every open.",
      "The /custom/ import preview now shows exactly what cleanup changed -- one row per rule, with counts -- and a 'Clean up OCR noise' checkbox to refuse it. Works for uploads and for pasted text alike, and the choice is stored per text, so display never silently undoes your answer.",
      "Running heads and page numbers are stripped from scanned PDFs. A scanned book repeats its title and folio at the edge of every page, and the text layer hands them back mid-sentence ('...dont je ne pus m'expli- 10 LE JOURNAL D'UNE FEMME DE CHAMBRE quer la double expression...'). Page numbers are digits-only (roman numerals count only when the book actually paginates in roman -- 'Il', 'did' and 'mix' are words, not folios), and the scanner's ~50 misspellings of a head are fuzzy-clustered so they fall together. On the reference scan this took headed pages from 445 of 530 to 27, with chapter numbers, diary dates, refrains and speaker names all intact.",
      "Japanese and Chinese texts now split into segments. Those scripts put no space after a full stop, so the sentence-boundary regex never matched and a whole book arrived as one giant segment. CJK boundaries are recognized, over-long sentences are cut at the segment cap, and segments are joined without inventing a space mid-sentence.",
      "Custom texts get a reader header on the practice page -- title, author when known, and 'Segment N of M' -- mirroring the library book header. Quotes and poems keep their attribution header instead; single-segment texts skip the pointless 'Segment 1 of 1'.",
      "Project Gutenberg license apparatus purged from the bundled library: 59 books cleaned, ~70,000 characters of boilerplate removed. Root cause was a one-character regex bug -- the start-of-text banner wraps onto two lines and '.' does not cross a newline, so the header stripper silently matched nothing and the full license shipped as chapters 11-20 of At the Mountains of Madness. Six genuine 'Gutenberg' mentions in the authors' own prose (Hugo, Joyce) are allowlisted and untouched.",
      "Untypeable typography in the library mapped to what a keyboard makes: coordinate primes to quotes (47\u00b0 24\u2032 becomes 47\u00b0 24'), vulgar fractions spelled out (size 1\u215c becomes size 1 3/8), dimension signs to x. Nine characters stay by design because they are the text -- Poe's Gold-Bug cryptogram symbols, the cross in Monte Cristo's will, Joyce's episcopal \u2720, and the big full stop that ends the Ithaca episode of Ulysses.",
      "A typeability census now gates the corpus: every character that can reach the typing surface is either ASCII, a letter in some script, allowlisted CJK punctuation, or individually pinned with a written justification. The next untypeable character fails the build instead of waiting for a user to notice it mid-sentence.",
    ],
  },
  {
    date: "2026-09-01",
    title: "Import your own books, adaptive practice, numpad, fonts, three new games",
    tag: "v0.6",
    notes: [
      "EPUB and PDF import on /custom/. Drop a whole book; it is parsed in the browser (nothing uploaded anywhere), split into ~500-character segments at sentence boundaries, and stored locally. PDF words are rejoined by measuring glyph geometry instead of gluing fragments with spaces, so text no longer arrives as 'beca use' -- and accented words stopped gaining spaces, because a PDF draws the accent by jumping backwards over the letter.",
      "Custom texts moved from localStorage to IndexedDB. The old shared 5 MB budget capped a text at 512 KB -- a 600-page PDF was silently cut a third of the way in. The ceiling is now ~12 MB of text per book, truncation is reported instead of silent, and a fallback path still works where IndexedDB is refused.",
      "Imported text is typeable text: non-breaking/thin/figure spaces become real spaces, zero-width characters and soft hyphens are removed, accents are composed to real letters (NFC), and words broken across lines rejoin without gaining a space -- including accented words, which the ASCII-only pattern used to miss.",
      "A segment picker for long texts: search and jump to any of a book's thousands of segments instead of pressing 'next' 3,900 times. The results screen offers 'Next segment', and progress resumes where you left off.",
      "A custom text pinned as a lesson is now tracked like one -- its own WPM history, mastery state, and panel in lesson trends, namespaced so an imported novel can never count toward 'finish every lesson'.",
      "Adaptive drills and an adaptive lesson curriculum: drills add repetitions of the characters you are worst at while still covering every word in the set, and key-set lessons weight their picker toward your slow keys and bigrams.",
      "Numpad: a full 10-key layout with correct finger mapping, six numpad drills, and numpad support in the live keyboard and the stats heatmap.",
      "Eleven typing fonts -- Fira Code, IBM Plex Mono, Iosevka, Cascadia Code, Roboto Mono, Source Code Pro, Ubuntu Mono, Space Mono, Inconsolata and Cousine join JetBrains Mono.",
      "Three new games: Punctuation Storm (punctuation-heavy fragments in four lanes, combos and shields), Word Snake, and Boss Battle -- plus power-ups in Catch the Word (time-freeze, screen-clear).",
      "Caret fixes for proportional rendering and caret-follow during fast typing, plus a typing-surface performance pass.",
      "Lesson trends redrawn as small multiples -- one panel per lesson, WPM and accuracy on a shared scale.",
      "Content quality passes over quotes, idioms and poetry: misattributions dropped, duplicates merged, formatting restored.",
      "Book reader: chapter navigation improvements and layout fixes; megamenu scrolling fixed on short viewports.",
      "The test suite got honest: gate scripts now prove a bug existed before asserting it fixed, assert exact strings rather than 'contains', and are checked by reverting the fix to confirm they go red. Several guards that could not fail were rewritten.",
    ],
  },
  {
    date: "2026-05-11",
    title: "Tape mode, games depth, mobile toolbar, Umami live, red gorilla favicon",
    tag: "v0.5",
    notes: [
      "Tape (ticker) mode: words scroll horizontally as the caret advances. JS rAF-driven slide (lerp 0.28/frame) — no CSS transition jank, math is char[0]-anchored so getBoundingClientRect mid-animation reads stay correct. 15-second default. Hero now leads with the tape sprint CTA.",
      "Games: per-mode high scores tracked separately in profile.gameStats.byMode (classic / endless / shooter). Best chip in the in-game HUD reflects current mode and flips on mode-tab switch. /games/ hub paints each card's personal best + best streak.",
      "Visible combo multiplier in game stage HUD — 1.5x at streak 5, 2x at 10, 3x at 20, 5x at 40. Color escalates accent → orange → red. Multiplier now actually applies to score math (was hardcoded 1.5x before).",
      "Score-pulse animation: each score increment fires a 360 ms scale + accent-glow on the Score number.",
      "Game-over overlay: new-best detection adds 'New best!' headline + 'Personal <mode> best' chip. Falling-short rounds show your current best + 'need X more' hint.",
      "Falling words no longer slide into the input box — miss-check pulled up to stageH - 80 px; shooter band trimmed to stageH - 160 so horizontal drift can't overlap the input either.",
      "Word Shooter mode added (mode=shooter): words drift across the screen horizontally; type to shoot them down before they leave the frame. Plane-crash explosion animation on catch.",
      "Endless mode added (mode=endless): no 3-miss cap, faster ramp. Persistent high score.",
      "Catch on game-input mobile typing now uses the OS soft keyboard (inputmode='text') — old custom virtual keyboard mount was unreliable and covered the stage.",
      "World-class mobile practice toolbar: stats row + 'current mode' summary chip. Tapping the chip opens a full bottom-sheet mode picker with every mode / variant / source. Old horizontally-scrolling chip strip + scroll-arrow chrome gone.",
      "Mobile sheet sized to 62 vh max so it lives in the lower portion of the screen — toolbar and typing surface stay visible above it.",
      "Definitive tap-to-type pause guard: engine.pauseTimer() itself rejects any pause request within 450 ms of the last keystroke. No code path can pause mid-typing regardless of what triggered it.",
      "Service-worker auto-update: registered with updateViaCache:'none' so new sw.js bypasses the HTTP cache; controllerchange listener auto-reloads the page once the new worker takes over. End of stale-cache 'fix shipped locally but not live' divergence.",
      "Comprehensive Umami event tracking — sessions, modes, variants, sources, library opens, lessons, challenges, achievements, theme/font/caret changes, exports, perf LCP buckets, external link clicks, PWA installs. ~50 named events.",
      "Public Umami dashboard embedded at /analytics/ — the same view I look at, no login.",
      "Red gorilla favicon: brand mark (gorilla + keyboard) re-colored to brand red across 16/32/48/64/180/192/256/512 PNGs. Generated by scripts/gen-red-favicons.mjs.",
      "Footer: all 9 link sections (7 megamenu + Project + Resources) lay out in a single row at >=1180px. Status badges (License, Source, Hosting, Last update, Privacy, Cost) restored to multi-row; all six are now links.",
      "Privacy badge says 'no cookies' (truthful — Umami is cookieless but it IS tracking; 'no tracking' overstated).",
      "Megamenu: dead drill IDs fixed (code-js/py/html → code-js-keywords/py-decorators/html-tags); Word Shooter + Endless now in the Games > Play column; 'Game roadmap' link removed (no such page).",
      "Achievements panel dedup: catalog had 3 entries sharing id='acc-99' so 'Three-nines — 99%' appeared three times in the celebration card. evaluate() now uses a Set to skip any id already processed.",
      "Build stability: eleventy.before hook pre-creates every _site/library/<slug>/ directory before pagination writes — fixes Windows/OneDrive ENOENT race when ~290 paginated library pages mkdir in parallel.",
      "Mobile fixes: ticker strip right-edge cutoff (min-width:0 on flex children), hero 'Or pick a different start' wraps cleanly (flex-wrap + white-space:nowrap on chips), testimonial prompt no longer wraps to 2 lines (shorter copy + non-wrapping link).",
    ],
  },
  {
    date: "2026-05-08",
    title: "Contribute system, blog, completion tracking, fullscreen, modal swap",
    tag: "v0.4",
    notes: [
      "/contribute/ hub with eight Web3Forms-backed forms: quote, book, parable, idiom, poem, drill, testimonial, thanks-note",
      "Smart /thank-you/ confirmation page tailors its message based on ?for=<kind>",
      "/reviews/ and /thanks-wall/ public pages -- approval-required curation via _data/reviews.js and _data/thanks_notes.js",
      "Per-corpus 'Suggest a...' CTAs at the bottom of /quotes/, /idioms/, /parables/, /poetry/, /library/, /drills/",
      "Megamenu and footer gained a Contribute column",
      "Post-session inline 'Leave a testimonial' prompt after 10+ lifetime sessions, dismissable",
      "/blog/ launched with Atom RSS at /feed.xml, tag pages, sticky TOC, reading-progress bar, social share, drop cap, prev/next nav",
      "Three starter posts: contribute system, completion tracking, why no em-dash",
      "Completion tracking rewritten -- only items typed all-the-way-through (endCursor >= targetLen) at >=80% accuracy mark complete",
      "Per-item and bulk reset on every corpus page (quotes, idioms, parables, poetry) and book detail page",
      "corpusProgress slice on every profile mirrors bookProgress: { quote, idiom, parable, poem }",
      "Native confirm() and prompt() replaced site-wide with styled <dialog> modals -- focus-trapped, theme-aware, cancel auto-focused on destructive actions",
      "Em-dashes (--) replaced with ASCII double-hyphen across UI, content, lessons, drills, megamenu, and book ingest pipeline",
      "Paragraph breaks now visible during book typing -- engine renders each paragraph as a block element with one space char joining them",
      "Engine now exposes endCursor + targetLen + book mode in finish triggers",
      "Contextual back link above the typing surface -- 'Back to quotes / idioms / parables / poetry / book / lessons / custom'",
      "Attribution header above quote/parable/poem/idiom typing -- title, author, year, source, meaning",
      "Tab+Enter restart replaces Alt+R -- two-key combo prevents accidental restart and avoids NVIDIA overlay collision",
      "Header gained a Fullscreen button (Lucide maximize-2 icon) right of Settings, toggles native Fullscreen API",
      "Streak chip simplified -- 'X day' instead of 'X day streak'",
      "Footer fits all 7 columns on one row at >=1180px (container widens to 96vw, max 1480px)",
      "Home page typing surface restored -- daily quote is now typeable inline, finish jumps to /practice/ for full results",
      "Weak-keys widget on the results card now session-scoped (filters out chars not in the just-typed target)",
      "Fixed mode-best card overflow at narrow viewports (220px min, flex-wrap on values, ellipsis on long labels)",
      "Default preferences flipped -- virtual keyboard ON, finger colors ON (v3 -> v4 migration)",
      "Quotes page is full-width with 'Type this' + 'Save to collection' actions, Random quote button, no pangrams in quote data",
    ],
  },
  {
    date: "2026-05-07",
    title: "Site named: GuerillaType",
    tag: "v0.3",
    notes: [
      "New name: GuerillaType at guerillatype.com",
      "New brand mark, favicon set, and OG card",
      "Toolbar groups now have visible legends — Mode, Duration, Word count, Quote length",
      "Live stats: third metric label changes per mode (seconds left / words typed / complete %)",
      "Keyboard shortcuts overlay (press ? or Ctrl+/) with g-prefix navigation",
      "Daily streak chip in the header (when ≥ 1 day)",
      "Session WPM-over-time mini chart in the results card",
      "Sticky-TOC click now scrolls to the precise section (header offset accounted for)",
      "Lesson, drill, and adaptive sessions now save properly (auto-finish at end)",
      "Heatmap visualizes keys with ≥ 2 samples (was ≥ 5) so first sessions show data",
    ],
  },
  {
    date: "2026-05-07",
    title: "Editorial pivot, megamenus, and informative pages",
    tag: "v0.2",
    notes: [
      "New visual identity: warm-paper editorial palette, persimmon accent, Lora serif display",
      "Megamenu nav with categorized sub-links (Practice, Learn, Compete, Insights)",
      "Daily quote on the home page — one curated quote per visitor per day",
      "Lessons now genuinely restrict the typing surface to their declared key set",
      "Backspace in the engine no longer freezes the keystroke pipeline",
      "New informative pages: Features, Tech stack, Analytics, Cost — all with sticky TOCs",
      "About, FAQ, Privacy, Terms rewritten and migrated to article layout",
    ],
  },
  {
    date: "2026-05-07",
    title: "Initial release",
    tag: "v0.1",
    notes: [
      "Practice modes: time, words, quote, zen, custom, adaptive",
      "Adaptive engine with weak-key + bigram targeting",
      "Custom text upload and saved-text manager",
      "Stats dashboard: lifetime totals, trend chart, contribution grid, keyboard heatmap, per-key bars",
      "Eleven challenges shipped, including code mode and mountain climb",
      "Four keyboard layouts (QWERTY/Dvorak/Colemak/Workman) for heatmap rendering",
      "Profiles with JSON export/import. localStorage only, no accounts.",
    ],
  },
];
